Rapper.create!(name:"2 chainz", age: 41, fire: true)
Rapper.create!(name:"Childish Gambino", age: 35, fire: true)
Rapper.create!(name:"Lupe Fiasco", age: 37, fire: true)
Rapper.create!(name:"Jay-Z", age: 49, fire: true)
Rapper.create!(name:"Lauryn Hill", age: 44, fire: true)
Rapper.create!(name:"Missy Elliott", age: 47, fire: true)
Rapper.create!(name:"T-Pain", age: 33, fire: false)
Rapper.create!(name:"Lil Wayne", age: 36, fire: true)
Rapper.create!(name:"James D-train Williams", age: 57, fire: false)
Rapper.create!(name:"Ice Cube", age: 49, fire: true)

Song.create!(name: "It's a Vibe",artist:"2 chainz", fire: true)
Song.create!(name: "3005",artist:"Childish Gambino", fire: true)
Song.create!(name: "Cool",artist:"Lupe Fiasco", fire: true)
Song.create!(name: "Lost One",artist:"Jay-Z", fire: true)
Song.create!(name: "Miss Educated",artist:"Lauryn Hill", fire: true)
Song.create!(name: "Work It",artist:"Missy Elliott", fire: true)
Song.create!(name: "Buy You a Drink",artist:"T-Pain", fire: false)
Song.create!(name: "Mr. Carter",artist:"Lil Wayne", fire: true)
Song.create!(name: "Poke",artist:"James D-train Williams", fire: false)
Song.create!(name: "It was a Good
  Day",artist:"Ice Cube", fire: true)
